// Minimal country name → ISO 3166-1 alpha-2 mapping used for flag-icons.
// Handles common aliases; falls back to first-two-letters if unknown.

const MAP: Record<string, string> = {
  "afghanistan": "af",
  "albania": "al",
  "algeria": "dz",
  "argentina": "ar",
  "armenia": "am",
  "australia": "au",
  "austria": "at",
  "azerbaijan": "az",
  "bahamas": "bs",
  "bahrain": "bh",
  "bangladesh": "bd",
  "belarus": "by",
  "belgium": "be",
  "bhutan": "bt",
  "bolivia": "bo",
  "bosnia": "ba",
  "bosnia and herzegovina": "ba",
  "brazil": "br",
  "bulgaria": "bg",
  "cambodia": "kh",
  "cameroon": "cm",
  "canada": "ca",
  "chile": "cl",
  "china": "cn",
  "colombia": "co",
  "costa rica": "cr",
  "croatia": "hr",
  "cuba": "cu",
  "cyprus": "cy",
  "czechia": "cz",
  "czech republic": "cz",
  "denmark": "dk",
  "dominican republic": "do",
  "ecuador": "ec",
  "egypt": "eg",
  "estonia": "ee",
  "ethiopia": "et",
  "finland": "fi",
  "france": "fr",
  "georgia": "ge",
  "germany": "de",
  "ghana": "gh",
  "greece": "gr",
  "guatemala": "gt",
  "hong kong": "hk",
  "hungary": "hu",
  "iceland": "is",
  "india": "in",
  "indonesia": "id",
  "iran": "ir",
  "iraq": "iq",
  "ireland": "ie",
  "israel": "il",
  "italy": "it",
  "jamaica": "jm",
  "japan": "jp",
  "jordan": "jo",
  "kazakhstan": "kz",
  "kenya": "ke",
  "kuwait": "kw",
  "kyrgyzstan": "kg",
  "laos": "la",
  "latvia": "lv",
  "lebanon": "lb",
  "libya": "ly",
  "lithuania": "lt",
  "luxembourg": "lu",
  "macau": "mo",
  "madagascar": "mg",
  "malaysia": "my",
  "maldives": "mv",
  "malta": "mt",
  "mexico": "mx",
  "monaco": "mc",
  "mongolia": "mn",
  "montenegro": "me",
  "morocco": "ma",
  "myanmar": "mm",
  "burma": "mm",
  "nepal": "np",
  "netherlands": "nl",
  "holland": "nl",
  "new zealand": "nz",
  "nigeria": "ng",
  "north korea": "kp",
  "norway": "no",
  "oman": "om",
  "pakistan": "pk",
  "panama": "pa",
  "paraguay": "py",
  "peru": "pe",
  "philippines": "ph",
  "poland": "pl",
  "portugal": "pt",
  "puerto rico": "pr",
  "qatar": "qa",
  "romania": "ro",
  "russia": "ru",
  "russian federation": "ru",
  "saudi arabia": "sa",
  "senegal": "sn",
  "serbia": "rs",
  "singapore": "sg",
  "slovakia": "sk",
  "slovenia": "si",
  "south africa": "za",
  "south korea": "kr",
  "korea": "kr",
  "spain": "es",
  "sri lanka": "lk",
  "sweden": "se",
  "switzerland": "ch",
  "syria": "sy",
  "taiwan": "tw",
  "tanzania": "tz",
  "thailand": "th",
  "tunisia": "tn",
  "turkey": "tr",
  "türkiye": "tr",
  "uganda": "ug",
  "ukraine": "ua",
  "united arab emirates": "ae",
  "uae": "ae",
  "united kingdom": "gb",
  "uk": "gb",
  "great britain": "gb",
  "england": "gb",
  "scotland": "gb",
  "wales": "gb",
  "northern ireland": "gb",
  "united states": "us",
  "united states of america": "us",
  "usa": "us",
  "us": "us",
  "america": "us",
  "uruguay": "uy",
  "uzbekistan": "uz",
  "venezuela": "ve",
  "vietnam": "vn",
  "yemen": "ye",
  "zimbabwe": "zw",
};

export function countryToIso2(name?: string | null): string | null {
  if (!name) return null;
  const key = name.trim().toLowerCase();
  if (!key) return null;
  if (MAP[key]) return MAP[key];
  // Try strip parenthetical, e.g. "United States (US)"
  const stripped = key.replace(/\(.*?\)/g, "").trim();
  if (MAP[stripped]) return MAP[stripped];
  return null;
}
