project_id = "vtblupfehbkrbnsdrrfq"

[functions.search-titles]
verify_jwt = false

[functions.search-locations]
verify_jwt = false

[functions.title-details]
verify_jwt = false

[functions.location-details]
verify_jwt = false

[functions.spot-details]
verify_jwt = false

[functions.weekly-movies]
verify_jwt = false
[functions.reveal-cards]
verify_jwt = false

[functions.related-titles]
verify_jwt = false

[functions.related-locations]
verify_jwt = false

[functions.passport-stamp-art]
verify_jwt = true

[functions.title-enrichment-vertex]
verify_jwt = false

